name=powietrze-level2-sink
connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
tasks.max=1
topics=powietrze-poziom2

connection.url=jdbc:mysql://mysql:3306/streamdb
connection.user=streamuser
connection.password=stream

table.name.format=powietrze_poziom2
insert.mode=upsert
pk.mode=record_key
pk.fields=report_date,station_type,wind_sector
delete.enabled=false