kafka.bootstrap.servers=localhost:9092
kafka.topic.powietrze=powietrze-odczyty
kafka.topic.air.stations=powietrze-slownik-stacje
kafka.topic.level1=powietrze-poziom1
kafka.topic.level2=powietrze-poziom2
kafka.topic.alerts=powietrze-alarmy
streams.application.id=powietrze-streams-app
streams.auto.offset.reset=earliest
streams.commit.interval.ms=10000
streams.window.size.ms=60000
streams.window.grace.ms=35000
streams.processing.guarantee=exactly_once_v2
streams.isolation.level=read_committed
level2.hll.log2m=12
alerts.pm25.unhealthy.threshold=55
alerts.pm25.very.unhealthy.threshold=150
alerts.counter.window.ms=300000
alerts.counter.grace.ms=35000
alerts.counter.min.count=3